// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Comprar Passagem', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Comprar Passagem', async function() {
    await driver.get("https://blazedemo.com/")
    await driver.manage().window().setRect({ width: 1149, height: 816 })
    assert(await driver.findElement(By.css("h1")).getText() == "Welcome to the Simple Travel Agency!")
    {
      const dropdown = await driver.findElement(By.name("fromPort"))
      await dropdown.findElement(By.xpath("//option[. = 'São Paolo']")).click()
    }
    {
      const dropdown = await driver.findElement(By.name("toPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Rome']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    assert(await driver.findElement(By.css("h3")).getText() == "Flights from São Paolo to Rome:")
    assert(await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(3)")).getText() == "43")
    await driver.findElement(By.css("tr:nth-child(1) .btn")).click()
    assert(await driver.findElement(By.css("h2")).getText() == "Your flight from TLV to SFO has been reserved.")
    await driver.findElement(By.id("inputName")).sendKeys("Vincent V. Gogh")
    await driver.findElement(By.id("address")).sendKeys("Rua Augusta")
    await driver.findElement(By.id("city")).sendKeys("São Paulo")
    await driver.findElement(By.id("state")).sendKeys("São Paulo")
    await driver.findElement(By.id("zipCode")).sendKeys("1304001")
    await driver.findElement(By.id("creditCardNumber")).sendKeys("12345678910121316")
    await driver.findElement(By.id("creditCardMonth")).sendKeys("09")
    await driver.findElement(By.id("creditCardYear")).sendKeys("2030")
    await driver.findElement(By.id("nameOnCard")).sendKeys("Vincent V. Gogh")
    await driver.findElement(By.css(".btn-primary")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Thank you for your purchase today!")
    await driver.findElement(By.linkText("Travel The World")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Welcome to the Simple Travel Agency!")
  })
})
